In [22]:
import numpy as np
import matplotlib.pyplot as plt
#%pylab inline
import random

# parameters
gridSize = 4
states_terminal = [[0,0], [gridSize-1, gridSize-1]]
valid_actions = [[-1, 0], [1, 0], [0, 1], [0, -1]]
gamma = 0.1 # discount rate
currentReward = -1
#Those values seem to work well
numIterations = 100
alpha = 0.1 #exploration factor

# initialization
#Note: Shouldn't the Q matrix be of dimension mxn instead, where m is the size of the state space and n is the size of the action space?
Q = np.zeros((gridSize, len(valid_actions)))
states = [[i, j] for i in range(gridSize) for j in range(gridSize)]
print(states)

[[0, 0], [0, 1], [0, 2], [0, 3], [1, 0], [1, 1], [1, 2], [1, 3], [2, 0], [2, 1], [2, 2], [2, 3], [3, 0], [3, 1], [3, 2], [3, 3]]


In [23]:
from random import randrange, choice
def generateInitialState():
    #generate a random initial state
    #Pick any state but the terminal states
    initialState = randrange(1, gridSize**2 - 1)
    return states[initialState]

def generateNextAction(state):
    #generate a random action from the valid set of actions
    #Pick completely random with probability alpha being the exploration rate
    if np.random.uniform(0, 1) < alpha:
        nextAction = randrange(0, len(valid_actions))
        return nextAction
    #Pick from Q table otherwise
    #(From all currently possible actions, pick the one that maximises the reward for this specific state)
    nextAction = np.argmax(Q[state, :])
    return nextAction

# define the transition function from a given state and action
def getNextState(state, action):
    
    #define what happens when reaching a terminal state
    if state in states_terminal:
        return None, None
    
    # here you should complete this step, the transition step
    nextStateObj = [sum(result) for result in zip(state, valid_actions[action])]
    # if the agent reaches a wall 
    if -1 in nextStateObj or gridSize in nextStateObj:
        nextStateObj = state
        nextState = state
    else:
        nextState = nextStateObj
    return currentReward, nextState

In [24]:
for it in range(numIterations):
    currentState = generateInitialState()
    while True:
        currentAction = generateNextAction(currentState)
        reward, nextState = getNextState(currentState, currentAction)
        #complete the stop action if the agent reached the goal state
        if reward is None and nextState is None:
            break
        #update the Q-value function Q
        nextAction = generateNextAction(nextState)
        Q[currentState[0]][currentState[1]] = (1 - alpha) * Q[currentState[0]][currentState[1]] + alpha * (reward + gamma * Q[nextState[0]][nextState[1]])
        #assign as current state the next state
        currentState = nextState
print(Q)

IndexError: list index out of range

In [115]:
#Print the desired action for each state
for i in range(len(Q)):
    print("State: " + str(states[i]) + f" Action: {np.argmax(Q[i, :])}")

State: [0, 0] Action: 0
State: [0, 1] Action: 3
State: [0, 2] Action: 3
State: [0, 3] Action: 3
State: [1, 0] Action: 0
State: [1, 1] Action: 3
State: [1, 2] Action: 3
State: [1, 3] Action: 1
State: [2, 0] Action: 0
State: [2, 1] Action: 1
State: [2, 2] Action: 2
State: [2, 3] Action: 1
State: [3, 0] Action: 0
State: [3, 1] Action: 2
State: [3, 2] Action: 2
State: [3, 3] Action: 0


In [116]:
data = np.zeros((gridSize, gridSize))
for i in range(len(states)):
    data[states[i][0], states[i][1]] = np.argmax(Q[i, :])
print(data)
#0 = up, 1 = down, 2 = right, 3 = left

[[0. 3. 3. 3.]
 [0. 3. 3. 1.]
 [0. 1. 2. 1.]
 [0. 2. 2. 0.]]
